- src/localize/languages/nl.json
added nl.json to support the dutch language
> added dutch language

- src/styles.ts
> Reduce font size of clock to prevent wrapping

- src/clock-weather-card.ts
> Fix attribute 'animated_icon' not working

- src/localize/languages/uk.json
- src/localize/localize.ts
> Add Ukrainian translations

- README.md
- src/clock-weather-card.ts
- src/images.ts
- src/types.ts
- src/utils.ts
> Add support for hourly weather providers

- src/images.ts
> Fix snowy and snowy-rainy icons not working

- src/localize/languages/en.json
> Change exceptional weather from 'Chaos' to 'Exceptional'

- src/clock-weather-card.ts
Isolate rendering of different components
> Improve error handling

- README.md
- src/localize/languages/ru.json
- src/localize/localize.ts
> Add Russian translations

- src/clock-weather-card.ts
- src/types.ts
> Handle null values in forecast attributes

- src/clock-weather-card.ts
- src/helpers.ts
> Fix missing temp indicator when out of range

- src/localize/languages/it.json
> Add Italian translations

- README.md
- src/localize/languages/hu.json
- src/localize/localize.ts
> Add Hungarian translations

- README.md
- src/clock-weather-card.ts
- src/helpers.ts
- src/localize/languages/bg.json
- src/localize/languages/ca.json
- src/localize/languages/cz.json
- src/localize/languages/da.json
- src/localize/languages/de.json
- src/localize/languages/en.json
- src/localize/languages/es.json
- src/localize/languages/fr.json
- src/localize/languages/hu.json
- src/localize/languages/it.json
- src/localize/languages/kr.json
- src/localize/languages/nl.json
- src/localize/languages/no.json
- src/localize/languages/pl.json
- src/localize/languages/pt-br.json
- src/localize/languages/pt.json
- src/localize/languages/ru.json
- src/localize/languages/sk.json
- src/localize/languages/sv.json
- src/localize/languages/uk.json
- src/types.ts
> Add config param to configure data formatting

- README.md
> Fix wrong path in install section of README.md

- src/styles.ts
> Fix layout issues with old iOS Webkit version

- src/clock-weather-card.ts
> Fix zero degree temps not displayed properly

- README.md
> Amend installation documentation to add lovelace card via UI

- src/styles.ts
> Fix negative temperatures cut off

- README.md
- src/clock-weather-card.ts
> 127 day and night icon not working after ha restart

- src/clock-weather-card.ts
- src/types.ts
> Render card properly even if no temp available

- src/clock-weather-card.ts
> Fix error when using language English (US) in HA

- src/images.ts
> Fix bug where day icon was display on sunny weather

- src/styles.ts
> Fix card not expanding to full height

- src/localize/languages/da.json
> Add missing weekdays in Danish language

- README.md
- src/localize/languages/et.json
- src/localize/localize.ts
> Add Estonian language

- src/clock-weather-card.ts
> Specify card size

- README.md
- src/clock-weather-card.ts
- src/types.ts
> Add support for new weather service (`weather.get_forecast`)

- README.md
- src/clock-weather-card.ts
- src/types.ts
> Add configuration property to specify a `time zone`

- README.md
- src/localize/languages/is.json
- src/localize/localize.ts
I like your stylish weather card. I would like to add support for the icelandic language.
> Support for icelandic

- src/localize/languages/tr.json
- src/localize/localize.ts
Added Turkish language support:
- Created tr.json
- Updated localize.ts
> Added TR support

- src/clock-weather-card.ts
- src/images.ts
Use static svc icons instead of png ones when `animated` is set to `false`, so that resizing looks good
> feat: use svg for static icons

- README.md
- src/localize/languages/id.json
- src/localize/localize.ts
Adds Indonesian 🇮🇩  (`ID`) language translation.
> Add `ID` (Indonesian) Language 🇮🇩 

- src/localize/languages/zh-tw.json
Update zh-tw translation of new entities.
> fix: Update Taiwanese translations

- src/localize/languages/ru.json
"Feels like" translate into russian
> fix: Translate "Feels like" into Russian

- src/localize/languages/et.json
Missed this one yesterday.  Probably last one I can tackle.  Thanks for the awesome card!!
> Localize "feels like" for Estonian

- README.md
- src/localize/languages/hr.json
- src/localize/localize.ts
> add croatian translate

- src/localize/languages/zh-cn.json
fix: Update "Feels like" for cn
> fix: Update "Feels like" for cn

- src/clock-weather-card.ts
updated colors to match EPA colors from https://www.airnow.gov/aqi/aqi-basics/
> feat: Update AQI background colors to match airnow.gov

- src/clock-weather-card.ts
Rework the temperature bar by replacing the old gradientRange() and gradient() functions with the new createGradientString() that calculates all bar colors with relative positions directly from the gradientMap and outputs those relative positions to the css gradient. This fixes at least following:
- Position intermediate temperature colors correctly to prevent banding. In the old system intermediate colors were just spaced evenly.
- Start and end color linearization now works as expected even on the very small bars.
- If the start or end temperature is out of the gradientMap range, the closest color is now used for those values as well.
- Fix move-right, start-percent and end-percent to 2 decimals, which should be enough precision.
Hopefully I didn't miss any extreme cases. :sweat_smile: …
> Fix: Rework temperature bar gradient
